# Generated by Django 4.1.5 on 2023-03-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='paginas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
